services:
  queuedeck-dev:
    build: .
    container_name: queuedeck-dev
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOST: "0.0.0.0"
      PORT: "7071"
      APP_NAME: "QueueDeck v1-dev"

      # Security/session
      SECRET_KEY: "${SECRET_KEY}"
      #QD_ADMIN_USER: "${QD_ADMIN_USER}"
      #QD_ADMIN_PASS: "${QD_ADMIN_PASS}"
      DB_PATH: "/data/queuedb.sqlite"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:7071/health').read()\""]
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - "7072:7071"
    restart: unless-stopped
